# Generated by Django 4.2.11 on 2024-05-07 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacitacao', '0011_alter_autoavaliacao_atualizado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softskill',
            name='atualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soft_skills_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
